import matplotlib.pyplot as plt
import numpy as np


# This function performs linear transformation of X using the params

def y_hat(x, theta1, theta2):
    return theta1 * x + theta2

# Generate data for X using np.arange which generates array with values from 0 to not included 1 with step size of 0.01
X = np.arange(0, 1, 0.01)
# Y is generated by adding random noise to X using np..random.normal
Y = X + np.random.normal(0, 0.2, len(X))

# Plot the data
plt.scatter(X, Y)

# Plot the model's predictions
theta1 = 1.0
theta2 = 0.0
predictions = y_hat(X, theta1, theta2)
plt.plot(X, predictions, color='red')

plt.xlabel('x')
plt.ylabel('y')
plt.title('Model Predictions')
plt.legend()
plt.show()
